// Auto-extracted from CMakeLists.txt files in vendor/mozjs/src/
// Platform: WIN32, ION enabled, TRACE_LOGGING enabled

pub const js_sources_common = &[_][]const u8{
    // builtin/intl
    "js/src/builtin/intl/Collator.cpp",
    "js/src/builtin/intl/CommonFunctions.cpp",
    "js/src/builtin/intl/DateTimeFormat.cpp",
    "js/src/builtin/intl/IntlObject.cpp",
    "js/src/builtin/intl/NumberFormat.cpp",
    "js/src/builtin/intl/PluralRules.cpp",
    "js/src/builtin/intl/RelativeTimeFormat.cpp",
    "js/src/builtin/intl/SharedIntlData.cpp",
    // builtin
    "js/src/builtin/AtomicsObject.cpp",
    "js/src/builtin/DataViewObject.cpp",
    "js/src/builtin/Eval.cpp",
    "js/src/builtin/JSON.cpp",
    "js/src/builtin/MapObject.cpp",
    "js/src/builtin/ModuleObject.cpp",
    "js/src/builtin/Object.cpp",
    "js/src/builtin/Profilers.cpp",
    "js/src/builtin/Promise.cpp",
    "js/src/builtin/Reflect.cpp",
    "js/src/builtin/ReflectParse.cpp",
    "js/src/builtin/RegExp.cpp",
    "js/src/builtin/SIMD.cpp",
    "js/src/builtin/Stream.cpp",
    "js/src/builtin/String.cpp",
    "js/src/builtin/Symbol.cpp",
    "js/src/builtin/TestingFunctions.cpp",
    "js/src/builtin/TypedObject.cpp",
    "js/src/builtin/WeakMapObject.cpp",
    "js/src/builtin/WeakSetObject.cpp",
    // devtools
    "js/src/devtools/sharkctl.cpp",
    // ds
    "js/src/ds/Bitmap.cpp",
    "js/src/ds/LifoAlloc.cpp",
    "js/src/ds/MemoryProtectionExceptionHandler.cpp",
    // frontend
    "js/src/frontend/BytecodeCompiler.cpp",
    "js/src/frontend/BytecodeEmitter.cpp",
    "js/src/frontend/FoldConstants.cpp",
    "js/src/frontend/NameFunctions.cpp",
    "js/src/frontend/ParseNode.cpp",
    "js/src/frontend/Parser.cpp",
    "js/src/frontend/TokenStream.cpp",
    // gc
    "js/src/gc/Allocator.cpp",
    "js/src/gc/AtomMarking.cpp",
    "js/src/gc/Barrier.cpp",
    "js/src/gc/GC.cpp",
    "js/src/gc/GCTrace.cpp",
    "js/src/gc/Marking.cpp",
    "js/src/gc/Memory.cpp",
    "js/src/gc/Nursery.cpp",
    "js/src/gc/PublicIterators.cpp",
    "js/src/gc/RootMarking.cpp",
    "js/src/gc/Statistics.cpp",
    "js/src/gc/StoreBuffer.cpp",
    "js/src/gc/Tracer.cpp",
    "js/src/gc/Verifier.cpp",
    "js/src/gc/WeakMap.cpp",
    "js/src/gc/WeakMapPtr.cpp",
    "js/src/gc/Zone.cpp",
    "js/src/gc/ZoneGroup.cpp",
    // irregexp
    "js/src/irregexp/NativeRegExpMacroAssembler.cpp",
    "js/src/irregexp/RegExpAST.cpp",
    "js/src/irregexp/RegExpCharacters.cpp",
    "js/src/irregexp/RegExpEngine.cpp",
    "js/src/irregexp/RegExpInterpreter.cpp",
    "js/src/irregexp/RegExpMacroAssembler.cpp",
    "js/src/irregexp/RegExpParser.cpp",
    "js/src/irregexp/RegExpStack.cpp",
    // jit (shared)
    "js/src/jit/AliasAnalysis.cpp",
    "js/src/jit/AliasAnalysisShared.cpp",
    "js/src/jit/AlignmentMaskAnalysis.cpp",
    "js/src/jit/BacktrackingAllocator.cpp",
    "js/src/jit/Bailouts.cpp",
    "js/src/jit/BaselineBailouts.cpp",
    "js/src/jit/BaselineCacheIRCompiler.cpp",
    "js/src/jit/BaselineCompiler.cpp",
    "js/src/jit/BaselineDebugModeOSR.cpp",
    "js/src/jit/BaselineFrame.cpp",
    "js/src/jit/BaselineFrameInfo.cpp",
    "js/src/jit/BaselineIC.cpp",
    "js/src/jit/BaselineInspector.cpp",
    "js/src/jit/BaselineJIT.cpp",
    "js/src/jit/BitSet.cpp",
    "js/src/jit/BytecodeAnalysis.cpp",
    "js/src/jit/C1Spewer.cpp",
    "js/src/jit/CacheIR.cpp",
    "js/src/jit/CacheIRCompiler.cpp",
    "js/src/jit/CacheIRSpewer.cpp",
    "js/src/jit/CodeGenerator.cpp",
    "js/src/jit/CompileWrappers.cpp",
    "js/src/jit/Disassembler.cpp",
    "js/src/jit/EagerSimdUnbox.cpp",
    "js/src/jit/EdgeCaseAnalysis.cpp",
    "js/src/jit/EffectiveAddressAnalysis.cpp",
    "js/src/jit/ExecutableAllocator.cpp",
    "js/src/jit/FlowAliasAnalysis.cpp",
    "js/src/jit/FoldLinearArithConstants.cpp",
    "js/src/jit/InstructionReordering.cpp",
    "js/src/jit/Ion.cpp",
    "js/src/jit/IonAnalysis.cpp",
    "js/src/jit/IonBuilder.cpp",
    "js/src/jit/IonCacheIRCompiler.cpp",
    "js/src/jit/IonControlFlow.cpp",
    "js/src/jit/IonIC.cpp",
    "js/src/jit/IonOptimizationLevels.cpp",
    "js/src/jit/Jit.cpp",
    "js/src/jit/JitcodeMap.cpp",
    "js/src/jit/JitFrames.cpp",
    "js/src/jit/JitOptions.cpp",
    "js/src/jit/JitSpewer.cpp",
    "js/src/jit/JSJitFrameIter.cpp",
    "js/src/jit/JSONSpewer.cpp",
    "js/src/jit/LICM.cpp",
    "js/src/jit/Linker.cpp",
    "js/src/jit/LIR.cpp",
    "js/src/jit/LoopUnroller.cpp",
    "js/src/jit/Lowering.cpp",
    "js/src/jit/MacroAssembler.cpp",
    "js/src/jit/MCallOptimize.cpp",
    "js/src/jit/MIR.cpp",
    "js/src/jit/MIRGraph.cpp",
    "js/src/jit/MoveResolver.cpp",
    "js/src/jit/OptimizationTracking.cpp",
    "js/src/jit/PerfSpewer.cpp",
    "js/src/jit/ProcessExecutableMemory.cpp",
    "js/src/jit/RangeAnalysis.cpp",
    "js/src/jit/Recover.cpp",
    "js/src/jit/RegisterAllocator.cpp",
    "js/src/jit/RematerializedFrame.cpp",
    "js/src/jit/Safepoints.cpp",
    "js/src/jit/ScalarReplacement.cpp",
    "js/src/jit/shared/Assembler-shared.cpp",
    "js/src/jit/shared/BaselineCompiler-shared.cpp",
    "js/src/jit/shared/CodeGenerator-shared.cpp",
    "js/src/jit/shared/Disassembler-shared.cpp",
    "js/src/jit/shared/Lowering-shared.cpp",
    "js/src/jit/SharedIC.cpp",
    "js/src/jit/Sink.cpp",
    "js/src/jit/Snapshots.cpp",
    "js/src/jit/StupidAllocator.cpp",
    "js/src/jit/TypedObjectPrediction.cpp",
    "js/src/jit/TypePolicy.cpp",
    "js/src/jit/ValueNumbering.cpp",
    "js/src/jit/VMFunctions.cpp",
    "js/src/jit/WasmBCE.cpp",
    // jit x86-shared (ION enabled)
    "js/src/jit/x86-shared/Architecture-x86-shared.cpp",
    "js/src/jit/x86-shared/Assembler-x86-shared.cpp",
    "js/src/jit/x86-shared/AssemblerBuffer-x86-shared.cpp",
    "js/src/jit/x86-shared/BaselineCompiler-x86-shared.cpp",
    "js/src/jit/x86-shared/BaselineIC-x86-shared.cpp",
    "js/src/jit/x86-shared/CodeGenerator-x86-shared.cpp",
    "js/src/jit/x86-shared/Disassembler-x86-shared.cpp",
    "js/src/jit/x86-shared/Lowering-x86-shared.cpp",
    "js/src/jit/x86-shared/MacroAssembler-x86-shared.cpp",
    "js/src/jit/x86-shared/MoveEmitter-x86-shared.cpp",
    // perf
    "js/src/perf/jsperf.cpp",
    "js/src/perf/pm_stub.cpp",
    // proxy
    "js/src/proxy/BaseProxyHandler.cpp",
    "js/src/proxy/CrossCompartmentWrapper.cpp",
    "js/src/proxy/DeadObjectProxy.cpp",
    "js/src/proxy/OpaqueCrossCompartmentWrapper.cpp",
    "js/src/proxy/Proxy.cpp",
    "js/src/proxy/ScriptedProxyHandler.cpp",
    "js/src/proxy/SecurityWrapper.cpp",
    "js/src/proxy/Wrapper.cpp",
    // threading
    "js/src/threading/Mutex.cpp",
    "js/src/threading/ProtectedData.cpp",
    // threading/windows (WIN32)
    "js/src/threading/windows/CpuCount.cpp",
    "js/src/threading/windows/Thread.cpp",
    // util
    "js/src/util/AllocPolicy.cpp",
    "js/src/util/DoubleToString.cpp",
    "js/src/util/NativeStack.cpp",
    "js/src/util/Printf.cpp",
    "js/src/util/StringBuffer.cpp",
    "js/src/util/Text.cpp",
    "js/src/util/Unicode.cpp",
    // vm
    "js/src/vm/ArgumentsObject.cpp",
    "js/src/vm/ArrayBufferObject.cpp",
    "js/src/vm/AsyncFunction.cpp",
    "js/src/vm/AsyncIteration.cpp",
    "js/src/vm/BytecodeUtil.cpp",
    "js/src/vm/Caches.cpp",
    "js/src/vm/CallNonGenericMethod.cpp",
    "js/src/vm/CharacterEncoding.cpp",
    "js/src/vm/CodeCoverage.cpp",
    "js/src/vm/Compression.cpp",
    "js/src/vm/DateTime.cpp",
    "js/src/vm/Debugger.cpp",
    "js/src/vm/DebuggerMemory.cpp",
    "js/src/vm/EnvironmentObject.cpp",
    "js/src/vm/ErrorObject.cpp",
    "js/src/vm/ErrorReporting.cpp",
    "js/src/vm/ForOfIterator.cpp",
    "js/src/vm/GeckoProfiler.cpp",
    "js/src/vm/GeneratorObject.cpp",
    "js/src/vm/GlobalObject.cpp",
    "js/src/vm/HelperThreads.cpp",
    "js/src/vm/Id.cpp",
    "js/src/vm/Initialization.cpp",
    "js/src/vm/Interpreter.cpp",
    "js/src/vm/Iteration.cpp",
    "js/src/vm/JSAtom.cpp",
    "js/src/vm/JSCompartment.cpp",
    "js/src/vm/JSContext.cpp",
    "js/src/vm/JSFunction.cpp",
    "js/src/vm/JSObject.cpp",
    "js/src/vm/JSONParser.cpp",
    "js/src/vm/JSONPrinter.cpp",
    "js/src/vm/JSScript.cpp",
    "js/src/vm/MemoryMetrics.cpp",
    "js/src/vm/NativeObject.cpp",
    "js/src/vm/ObjectGroup.cpp",
    "js/src/vm/PIC.cpp",
    "js/src/vm/Printer.cpp",
    "js/src/vm/Probes.cpp",
    "js/src/vm/ProxyObject.cpp",
    "js/src/vm/Realm.cpp",
    "js/src/vm/ReceiverGuard.cpp",
    "js/src/vm/RegExpObject.cpp",
    "js/src/vm/RegExpStatics.cpp",
    "js/src/vm/Runtime.cpp",
    "js/src/vm/SavedStacks.cpp",
    "js/src/vm/Scope.cpp",
    "js/src/vm/SelfHosting.cpp",
    "js/src/vm/Shape.cpp",
    "js/src/vm/SharedArrayObject.cpp",
    "js/src/vm/SharedImmutableStringsCache.cpp",
    "js/src/vm/Stack.cpp",
    "js/src/vm/Stopwatch.cpp",
    "js/src/vm/StringType.cpp",
    "js/src/vm/StructuredClone.cpp",
    "js/src/vm/SymbolType.cpp",
    "js/src/vm/TaggedProto.cpp",
    "js/src/vm/Time.cpp",
    "js/src/vm/TypedArrayObject.cpp",
    "js/src/vm/TypeInference.cpp",
    "js/src/vm/UbiNode.cpp",
    "js/src/vm/UbiNodeCensus.cpp",
    "js/src/vm/UbiNodeShortestPaths.cpp",
    "js/src/vm/UnboxedObject.cpp",
    "js/src/vm/Value.cpp",
    "js/src/vm/Xdr.cpp",
    // vm - trace logging (ENABLE_TRACE_LOGGING)
    "js/src/vm/TraceLogging.cpp",
    "js/src/vm/TraceLoggingGraph.cpp",
    "js/src/vm/TraceLoggingTypes.cpp",
    // wasm
    "js/src/wasm/AsmJS.cpp",
    "js/src/wasm/WasmBaselineCompile.cpp",
    "js/src/wasm/WasmBinaryIterator.cpp",
    "js/src/wasm/WasmBinaryToAST.cpp",
    "js/src/wasm/WasmBinaryToText.cpp",
    "js/src/wasm/WasmBuiltins.cpp",
    "js/src/wasm/WasmCode.cpp",
    "js/src/wasm/WasmCompartment.cpp",
    "js/src/wasm/WasmCompile.cpp",
    "js/src/wasm/WasmDebug.cpp",
    "js/src/wasm/WasmFrameIter.cpp",
    "js/src/wasm/WasmGenerator.cpp",
    "js/src/wasm/WasmInstance.cpp",
    "js/src/wasm/WasmIonCompile.cpp",
    "js/src/wasm/WasmJS.cpp",
    "js/src/wasm/WasmModule.cpp",
    "js/src/wasm/WasmProcess.cpp",
    "js/src/wasm/WasmSignalHandlers.cpp",
    "js/src/wasm/WasmStubs.cpp",
    "js/src/wasm/WasmTable.cpp",
    "js/src/wasm/WasmTextToBinary.cpp",
    "js/src/wasm/WasmTextUtils.cpp",
    "js/src/wasm/WasmTypes.cpp",
    "js/src/wasm/WasmValidate.cpp",
    // top-level
    "js/src/jsapi.cpp",
    "js/src/jsarray.cpp",
    "js/src/jsbool.cpp",
    "js/src/jsdate.cpp",
    "js/src/jsexn.cpp",
    "js/src/jsfriendapi.cpp",
    "js/src/jsmath.cpp",
    "js/src/jsnum.cpp",
    "js/src/jsutil.cpp",
};

// x86 (32-bit) JIT backend — use ONE of js_sources_jit_x86 or js_sources_jit_x64
pub const js_sources_jit_x86 = &[_][]const u8{
    "js/src/jit/x86/Assembler-x86.cpp",
    "js/src/jit/x86/Bailouts-x86.cpp",
    "js/src/jit/x86/BaselineCompiler-x86.cpp",
    "js/src/jit/x86/BaselineIC-x86.cpp",
    "js/src/jit/x86/CodeGenerator-x86.cpp",
    "js/src/jit/x86/Lowering-x86.cpp",
    "js/src/jit/x86/MacroAssembler-x86.cpp",
    "js/src/jit/x86/SharedIC-x86.cpp",
    "js/src/jit/x86/Trampoline-x86.cpp",
};

// x64 (64-bit) JIT backend
pub const js_sources_jit_x64 = &[_][]const u8{
    "js/src/jit/x64/Assembler-x64.cpp",
    "js/src/jit/x64/Bailouts-x64.cpp",
    "js/src/jit/x64/BaselineCompiler-x64.cpp",
    "js/src/jit/x64/BaselineIC-x64.cpp",
    "js/src/jit/x64/CodeGenerator-x64.cpp",
    "js/src/jit/x64/Lowering-x64.cpp",
    "js/src/jit/x64/MacroAssembler-x64.cpp",
    "js/src/jit/x64/SharedIC-x64.cpp",
    "js/src/jit/x64/Trampoline-x64.cpp",
};

pub const mfbt_sources = &[_][]const u8{
    // double-conversion (.cc files)
    "mfbt/double-conversion/bignum.cc",
    "mfbt/double-conversion/bignum-dtoa.cc",
    "mfbt/double-conversion/cached-powers.cc",
    "mfbt/double-conversion/diy-fp.cc",
    "mfbt/double-conversion/double-conversion.cc",
    "mfbt/double-conversion/fast-dtoa.cc",
    "mfbt/double-conversion/fixed-dtoa.cc",
    "mfbt/double-conversion/strtod.cc",
    // decimal
    "mfbt/decimal/Decimal.cpp",
    // top-level
    "mfbt/Assertions.cpp",
    "mfbt/ChaosMode.cpp",
    "mfbt/Compression.cpp",
    "mfbt/FloatingPoint.cpp",
    "mfbt/HashFunctions.cpp",
    "mfbt/JSONWriter.cpp",
    "mfbt/lz4.c",
    "mfbt/Poison.cpp",
    "mfbt/SHA1.cpp",
    "mfbt/TaggedAnonymousMemory.cpp",
    "mfbt/unused.cpp",
};

pub const nspr_sources = &[_][]const u8{
    // pr/src/io
    "nsprpub/pr/src/io/prdir.c",
    "nsprpub/pr/src/io/prfdcach.c",
    "nsprpub/pr/src/io/prfile.c",
    "nsprpub/pr/src/io/prio.c",
    "nsprpub/pr/src/io/priometh.c",
    "nsprpub/pr/src/io/pripv6.c",
    "nsprpub/pr/src/io/prlayer.c",
    "nsprpub/pr/src/io/prlog.c",
    "nsprpub/pr/src/io/prmapopt.c",
    "nsprpub/pr/src/io/prmmap.c",
    "nsprpub/pr/src/io/prmwait.c",
    "nsprpub/pr/src/io/prpolevt.c",
    "nsprpub/pr/src/io/prprf.c",
    "nsprpub/pr/src/io/prscanf.c",
    "nsprpub/pr/src/io/prsocket.c",
    "nsprpub/pr/src/io/prstdio.c",
    // pr/src/linking
    "nsprpub/pr/src/linking/prlink.c",
    // pr/src/malloc
    "nsprpub/pr/src/malloc/prmalloc.c",
    "nsprpub/pr/src/malloc/prmem.c",
    // pr/src/md/windows (WIN32)
    "nsprpub/pr/src/md/windows/ntmisc.c",
    "nsprpub/pr/src/md/windows/ntsec.c",
    "nsprpub/pr/src/md/windows/ntsem.c",
    "nsprpub/pr/src/md/windows/ntinrval.c",
    "nsprpub/pr/src/md/windows/ntgc.c",
    "nsprpub/pr/src/md/windows/w95thred.c",
    "nsprpub/pr/src/md/windows/w95io.c",
    "nsprpub/pr/src/md/windows/w95cv.c",
    "nsprpub/pr/src/md/windows/w95sock.c",
    "nsprpub/pr/src/md/windows/win32_errors.c",
    "nsprpub/pr/src/md/windows/w32ipcsem.c",
    "nsprpub/pr/src/md/windows/w32poll.c",
    "nsprpub/pr/src/md/windows/w32rng.c",
    "nsprpub/pr/src/md/windows/w32shm.c",
    "nsprpub/pr/src/md/windows/w95dllmain.c",
    "nsprpub/pr/src/md/prosdep.c",
    // pr/src/memory
    "nsprpub/pr/src/memory/prseg.c",
    "nsprpub/pr/src/memory/prshm.c",
    "nsprpub/pr/src/memory/prshma.c",
    // pr/src/misc
    "nsprpub/pr/src/misc/pralarm.c",
    "nsprpub/pr/src/misc/pratom.c",
    "nsprpub/pr/src/misc/praton.c",
    "nsprpub/pr/src/misc/prcountr.c",
    "nsprpub/pr/src/misc/prdtoa.c",
    "nsprpub/pr/src/misc/prenv.c",
    "nsprpub/pr/src/misc/prerr.c",
    "nsprpub/pr/src/misc/prerror.c",
    "nsprpub/pr/src/misc/prerrortable.c",
    "nsprpub/pr/src/misc/prinit.c",
    "nsprpub/pr/src/misc/prinrval.c",
    "nsprpub/pr/src/misc/pripc.c",
    "nsprpub/pr/src/misc/pripcsem.c",
    "nsprpub/pr/src/misc/prlog2.c",
    "nsprpub/pr/src/misc/prlong.c",
    "nsprpub/pr/src/misc/prnetdb.c",
    "nsprpub/pr/src/misc/prolock.c",
    "nsprpub/pr/src/misc/prrng.c",
    "nsprpub/pr/src/misc/prsystem.c",
    "nsprpub/pr/src/misc/prthinfo.c",
    "nsprpub/pr/src/misc/prtime.c",
    "nsprpub/pr/src/misc/prtpool.c",
    "nsprpub/pr/src/misc/prtrace.c",
    // pr/src/threads/combined
    "nsprpub/pr/src/threads/combined/prucpu.c",
    "nsprpub/pr/src/threads/combined/prucv.c",
    "nsprpub/pr/src/threads/combined/prulock.c",
    "nsprpub/pr/src/threads/combined/pruthr.c",
    "nsprpub/pr/src/threads/combined/prustack.c",
    // pr/src/threads
    "nsprpub/pr/src/threads/prcmon.c",
    "nsprpub/pr/src/threads/prdump.c",
    "nsprpub/pr/src/threads/prmon.c",
    "nsprpub/pr/src/threads/prsem.c",
    "nsprpub/pr/src/threads/prrwlock.c",
    "nsprpub/pr/src/threads/prcthr.c",
    "nsprpub/pr/src/threads/prtpd.c",
};

pub const nspr_libc_sources = &[_][]const u8{
    "nsprpub/lib/libc/src/plvrsion.c",
    "nsprpub/lib/libc/src/strlen.c",
    "nsprpub/lib/libc/src/strcpy.c",
    "nsprpub/lib/libc/src/strdup.c",
    "nsprpub/lib/libc/src/strcase.c",
    "nsprpub/lib/libc/src/strcat.c",
    "nsprpub/lib/libc/src/strcmp.c",
    "nsprpub/lib/libc/src/strchr.c",
    "nsprpub/lib/libc/src/strpbrk.c",
    "nsprpub/lib/libc/src/strstr.c",
    "nsprpub/lib/libc/src/strtok.c",
    "nsprpub/lib/libc/src/base64.c",
    "nsprpub/lib/libc/src/plerror.c",
    "nsprpub/lib/libc/src/plgetopt.c",
};

// intl/icu is INTERFACE only (headers, no compiled sources)
// ICU is linked externally or used header-only in this build

pub const mozglue_sources = &[_][]const u8{
    "mozglue/misc/AutoProfilerLabel.cpp",
    "mozglue/misc/ConditionVariable_windows.cpp",
    "mozglue/misc/Mutex_windows.cpp",
    "mozglue/misc/Printf.cpp",
    "mozglue/misc/StackWalk.cpp",
    "mozglue/misc/TimeStamp.cpp",
    "mozglue/misc/TimeStamp_windows.cpp",
};

pub const zlib_sources = &[_][]const u8{
    "modules/zlib/src/adler32.c",
    "modules/zlib/src/compress.c",
    "modules/zlib/src/crc32.c",
    "modules/zlib/src/deflate.c",
    "modules/zlib/src/gzclose.c",
    "modules/zlib/src/gzlib.c",
    "modules/zlib/src/gzread.c",
    "modules/zlib/src/gzwrite.c",
    "modules/zlib/src/infback.c",
    "modules/zlib/src/inffast.c",
    "modules/zlib/src/inflate.c",
    "modules/zlib/src/inftrees.c",
    "modules/zlib/src/trees.c",
    "modules/zlib/src/uncompr.c",
    "modules/zlib/src/zutil.c",
};

pub const fdlibm_sources = &[_][]const u8{
    "modules/fdlibm/src/e_acos.cpp",
    "modules/fdlibm/src/e_acosh.cpp",
    "modules/fdlibm/src/e_asin.cpp",
    "modules/fdlibm/src/e_atan2.cpp",
    "modules/fdlibm/src/e_atanh.cpp",
    "modules/fdlibm/src/e_cosh.cpp",
    "modules/fdlibm/src/e_exp.cpp",
    "modules/fdlibm/src/e_hypot.cpp",
    "modules/fdlibm/src/e_log.cpp",
    "modules/fdlibm/src/e_log10.cpp",
    "modules/fdlibm/src/e_log2.cpp",
    "modules/fdlibm/src/e_pow.cpp",
    "modules/fdlibm/src/e_sinh.cpp",
    "modules/fdlibm/src/e_sqrt.cpp",
    "modules/fdlibm/src/k_exp.cpp",
    "modules/fdlibm/src/s_asinh.cpp",
    "modules/fdlibm/src/s_atan.cpp",
    "modules/fdlibm/src/s_cbrt.cpp",
    "modules/fdlibm/src/s_ceil.cpp",
    "modules/fdlibm/src/s_ceilf.cpp",
    "modules/fdlibm/src/s_copysign.cpp",
    "modules/fdlibm/src/s_expm1.cpp",
    "modules/fdlibm/src/s_fabs.cpp",
    "modules/fdlibm/src/s_floor.cpp",
    "modules/fdlibm/src/s_floorf.cpp",
    "modules/fdlibm/src/s_log1p.cpp",
    "modules/fdlibm/src/s_nearbyint.cpp",
    "modules/fdlibm/src/s_rint.cpp",
    "modules/fdlibm/src/s_rintf.cpp",
    "modules/fdlibm/src/s_scalbn.cpp",
    "modules/fdlibm/src/s_tanh.cpp",
    "modules/fdlibm/src/s_trunc.cpp",
    "modules/fdlibm/src/s_truncf.cpp",
};

pub const mozalloc_sources = &[_][]const u8{
    "memory/mozalloc/mozalloc.cpp",
    "memory/mozalloc/mozalloc_abort.cpp",
    "memory/mozalloc/mozalloc_oom.cpp",
};

pub const mozmemory_sources = &[_][]const u8{
    "memory/build/fallback.cpp",
};

// fallible is INTERFACE only (no compiled sources)
